PRODUCT_PACKAGES += \
    ClearCallingSettingsOverlay2022 \
    CompanionDeviceManagerOverlay \
    DMServiceOverlay \
    DeviceDiagnosticsOverlay \
    FlipendoOverlay \
    NfcOverlayCommon \
    NfcOverlayPanther \
    PixelBatteryHealthOverlay \
    PixelConfigOverlay2021 \
    SafetyRegulatoryInfoOverlay \
    SettingsGoogleFuturePantherOverlay \
    SettingsGooglePantherOverlay \
    SettingsGooglepantherOverlayRRO \
    SettingsProviderOverlay \
    SimAppDialogOverlay \
    StorageManagerGoogleOverlay \
    SystemUIGoogleOverlay \
    TeleServiceOverlay \
    TelecomOverlay \
    TelephonyProviderOverlay \
    TraceurOverlay \
    TrafficLightFaceOverlay \
    UdfpsOverlay \
    WildlifeSettingsVpnOverlay2022 \
    WildlifeSysuiVpnOverlay2022 \
    SettingsGooglepantherOverlayVendorRRO \
    SystemUIGoogle__panther__auto_generated_rro_vendor \
    TeleService__panther__auto_generated_rro_vendor \
    framework-res__panther__auto_generated_rro_vendor \
