PRODUCT_PACKAGES += \
    ClearCallingSettingsOverlay2022 \
    CompanionDeviceManagerOverlay \
    DMServiceOverlay \
    DeviceDiagnosticsOverlay \
    FlipendoOverlay \
    NfcOverlayCheetah \
    NfcOverlayCommon \
    PixelBatteryHealthOverlay \
    PixelConfigOverlay2021 \
    SafetyRegulatoryInfoOverlay \
    SettingsGoogleCheetahOverlay \
    SettingsGoogleFutureCheetahOverlay \
    SettingsGoogleCheetahOverlayRRO \
    SettingsProviderOverlay \
    SimAppDialogOverlay \
    StorageManagerGoogleOverlay \
    SystemUIGoogleOverlay \
    TeleServiceOverlay \
    TelecomOverlay \
    TelephonyProviderOverlay \
    TraceurOverlay \
    TrafficLightFaceOverlay \
    UdfpsOverlay \
    WildlifeSettingsVpnOverlay2022 \
    WildlifeSysuiVpnOverlay2022 \
    SettingsGooglecheetahOverlayVendorRRO \
    SystemUIGoogle__cheetah__auto_generated_rro_vendor \
    TeleService__cheetah__auto_generated_rro_vendor \
    framework-res__cheetah__auto_generated_rro_vendor \
