PRODUCT_PACKAGES += \
    ClearCallingSettingsOverlay2022 \
    CompanionDeviceManagerOverlay \
    DMServiceOverlay \
    DeviceDiagnosticsOverlay \
    FlipendoOverlay \
    NfcOverlayCommon \
    NfcOverlayLynx \
    PixelBatteryHealthOverlay \
    PixelConfigOverlay2021 \
    SafetyRegulatoryInfoOverlay \
    SettingsGoogleFutureLynxOverlay \
    SettingsGoogleLynxOverlay \
    SettingsGooglelynxOverlayRRO \
    SettingsProviderOverlay \
    SimAppDialogOverlay \
    StorageManagerGoogleOverlay \
    SystemUIGoogleOverlay \
    TeleServiceOverlay \
    TelecomOverlay \
    TelephonyProviderOverlay \
    TraceurOverlay \
    TrafficLightFaceOverlay \
    UdfpsOverlay \
    WildlifeSettingsVpnOverlay2022 \
    WildlifeSysuiVpnOverlay2022 \
    SettingsGooglelynxOverlayVendorRRO \
    SystemUIGoogle__lynx__auto_generated_rro_vendor \
    TeleService__lynx__auto_generated_rro_vendor \
    framework-res__lynx__auto_generated_rro_vendor \
